import { limparNomeFazenda } from "./fazendas";

/** Valor de uma célula já normalizado: texto sem espaços sobrando, número ou "" */
/** minúsculas, sem acento e sem pontuação: "Código Cliente/Forn." -> "codigo cliente forn" */
export function normalizarTexto(s) {
  return s
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

const texto = (v) => (v === undefined ? "" : String(v)).trim();

export const CADASTROS_SPEC = [
  {
    slug: "fazendas",
    titulo: "Fazenda",
    arquivos: ["fazendas", "propriedades", "cadastro de propriedade"],
    obrigatorias: ["propriedade", "sequencia", "fundo_agricola"],
    codigo: (d) => `${texto(d.propriedade)}${Number(d.sequencia) ? `-${texto(d.sequencia)}` : ""}`,
    nome: (d) => texto(d.fundo_agricola),
    chaves: ["propriedade", "sequencia"],
    ajuste: {
      rotulo: "Corrigir Descrição Fazenda",
      descricao: "Tira números, espaços e traços antes do nome (ex.: “9386 - FAZ. NOSSA SENHORA” → “FAZ. NOSSA SENHORA”).",
      aplicar: (d) => ({ ...d, fundo_agricola: limparNomeFazenda(texto(d.fundo_agricola), texto(d.propriedade)) }),
    },
    colunas: [
      { chave: "propriedade", rotulo: "Propriedade", alinhar: "direita" },
      { chave: "sequencia", rotulo: "Seq.", alinhar: "direita" },
      { chave: "fundo_agricola", rotulo: "Descrição Fazenda", largura: 260 },
      { chave: "proprietario", rotulo: "Código Proprietário", alinhar: "direita" },
      { chave: "proprietario_2", rotulo: "Proprietário", largura: 240 },
      { chave: "tipo_de_propriedade", rotulo: "Tipo", alinhar: "centro" },
      { chave: "area_ha", rotulo: "Área (ha)", alinhar: "direita" },
      { chave: "cidade", rotulo: "Cidade" },
      { chave: "uf", rotulo: "UF", alinhar: "centro" },
      { chave: "ativo", rotulo: "Ativo", alinhar: "centro" },
    ],
  },
  {
    slug: "fornecedores-prestadores",
    titulo: "Fornecedores e Prestadores",
    arquivos: ["prestadores e fornecedores", "fornecedores e prestadores", "fornecedores", "prestadores"],
    obrigatorias: ["codigo_cliente_forn", "nome"],
    codigo: (d) => texto(d.codigo_cliente_forn),
    nome: (d) => texto(d.nome),
    chaves: ["codigo_cliente_forn"],
    colunas: [
      { chave: "codigo_cliente_forn", rotulo: "Código", alinhar: "direita" },
      { chave: "nome", rotulo: "Nome", largura: 260 },
      { chave: "nome_fantasia", rotulo: "Nome Fantasia", largura: 200 },
      { chave: "cnpj_cpf", rotulo: "CNPJ/CPF" },
      { chave: "cidade", rotulo: "Cidade" },
      { chave: "uf", rotulo: "UF", alinhar: "centro" },
      { chave: "telefone_comercial", rotulo: "Telefone" },
      { chave: "bloqueado", rotulo: "Bloqueado", alinhar: "centro" },
    ],
  },
  {
    slug: "regiao",
    titulo: "Região",
    arquivos: ["regioes", "regiao"],
    obrigatorias: ["regiao", "nome"],
    codigo: (d) => texto(d.regiao),
    nome: (d) => texto(d.nome),
    chaves: ["regiao"],
    colunas: [
      { chave: "regiao", rotulo: "Região", alinhar: "direita" },
      { chave: "nome", rotulo: "Nome", largura: 240 },
    ],
  },
  {
    slug: "bloco",
    titulo: "Bloco",
    arquivos: ["blocos", "bloco", "setores"],
    obrigatorias: ["setor", "descricao", "grau"],
    // o mesmo setor aparece com mais de uma descrição: a chave é o par
    codigo: (d) => `${texto(d.setor)}|${texto(d.descricao)}`,
    nome: (d) => texto(d.descricao),
    chaves: ["setor", "descricao"],
    colunas: [
      { chave: "setor", rotulo: "Setor" },
      { chave: "descricao", rotulo: "Descrição", largura: 280 },
      { chave: "grau", rotulo: "Grau", alinhar: "direita" },
      { chave: "regiao", rotulo: "Região (código)", largura: 130, ref: "regiao" },
      { chave: "regiao_nm", rotulo: "Descrição da Região", largura: 220, derivada: true },
    ],
  },
  {
    slug: "estados",
    titulo: "Estados",
    arquivos: ["estados"],
    obrigatorias: ["sigla_do_estado", "nome_do_estado"],
    codigo: (d) => texto(d.sigla_do_estado),
    nome: (d) => texto(d.nome_do_estado),
    chaves: ["sigla_do_estado"],
    colunas: [
      { chave: "sigla_do_estado", rotulo: "Sigla", alinhar: "centro" },
      { chave: "nome_do_estado", rotulo: "Nome do Estado", largura: 200 },
      { chave: "codigo_u_f", rotulo: "Código UF", alinhar: "direita" },
      { chave: "codigo_ibge", rotulo: "Código IBGE", alinhar: "direita" },
      { chave: "possui_zfm_alc", rotulo: "ZFM/ALC", alinhar: "centro" },
    ],
  },
  {
    slug: "solos",
    titulo: "Solos",
    arquivos: ["solos", "solo"],
    obrigatorias: ["codigo", "descricao", "tipo_de_solo"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.descricao),
    chaves: ["codigo"],
    colunas: [
      { chave: "codigo", rotulo: "Código", alinhar: "direita" },
      { chave: "descricao", rotulo: "Descrição", largura: 240 },
      { chave: "tipo_de_solo", rotulo: "Tipo de Solo", alinhar: "direita" },
      { chave: "descricao_do_tipo", rotulo: "Descrição do Tipo", largura: 200 },
      { chave: "acrescimo_de_produtividade", rotulo: "% Acréscimo de Produtividade", alinhar: "direita" },
    ],
  },
  {
    slug: "tipos-solo",
    titulo: "Tipos de Solo",
    arquivos: ["tipo de solo", "tipos de solo", "tipos de solos"],
    obrigatorias: ["codigo", "descricao"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.descricao),
    chaves: ["codigo"],
    colunas: [
      { chave: "codigo", rotulo: "Código", alinhar: "direita" },
      { chave: "descricao", rotulo: "Descrição", largura: 240 },
    ],
  },
  {
    slug: "maturacao",
    titulo: "Maturação",
    arquivos: ["maturacao"],
    obrigatorias: ["codigo", "descricao"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.descricao),
    chaves: ["codigo"],
    colunas: [
      { chave: "codigo", rotulo: "Código", alinhar: "direita" },
      { chave: "descricao", rotulo: "Descrição", largura: 240 },
    ],
  },
  {
    slug: "variedades",
    titulo: "Variedades",
    arquivos: ["variedades", "variedade"],
    obrigatorias: ["codigo", "descricao", "cortes_previstos"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.descricao),
    chaves: ["codigo"],
    colunas: [
      { chave: "codigo", rotulo: "Código", alinhar: "direita" },
      { chave: "descricao", rotulo: "Descrição", largura: 200 },
      { chave: "cortes_previstos", rotulo: "Cortes Previstos", alinhar: "direita" },
      { chave: "mat_tipo_ciclo", rotulo: "Código Maturação", alinhar: "direita" },
      { chave: "descricao_2", rotulo: "Maturação" },
      { chave: "ativa", rotulo: "Ativa", alinhar: "centro" },
    ],
  },
  {
    slug: "ocorrencias",
    titulo: "Ocorrências",
    arquivos: ["ocorrencias", "ocorrencia"],
    obrigatorias: ["codigo", "descricao"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.descricao),
    chaves: ["codigo"],
    colunas: [
      { chave: "codigo", rotulo: "Código", largura: 90 },
      { chave: "descricao", rotulo: "Descrição", largura: 320 },
    ],
  },
  {
    slug: "nivel-infestacao",
    titulo: "Nível de Infestação",
    arquivos: ["nivel de infestacao", "niveis de infestacao", "nivel infestacao"],
    obrigatorias: ["codigo", "descricao"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.descricao),
    chaves: ["codigo"],
    colunas: [
      { chave: "codigo", rotulo: "Código", largura: 90 },
      { chave: "descricao", rotulo: "Descrição", largura: 320 },
    ],
  },
  {
    slug: "presenca-infestacao",
    titulo: "Presença de Infestação",
    arquivos: ["presenca de infestacao", "presenca infestacao"],
    obrigatorias: ["codigo", "descricao"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.descricao),
    chaves: ["codigo"],
    colunas: [
      { chave: "codigo", rotulo: "Código", largura: 90 },
      { chave: "descricao", rotulo: "Descrição", largura: 320 },
    ],
  },
  {
    slug: "prioridade",
    titulo: "Prioridade",
    arquivos: ["prioridade", "prioridades"],
    obrigatorias: ["codigo", "descricao"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.descricao),
    chaves: ["codigo"],
    colunas: [
      { chave: "codigo", rotulo: "Código", largura: 90 },
      { chave: "descricao", rotulo: "Descrição", largura: 320 },
    ],
  },
  {
    slug: "responsavel-regiao",
    titulo: "Responsável Região",
    arquivos: ["responsavel regiao", "responsaveis regiao", "responsavel por regiao", "responsaveis"],
    obrigatorias: ["codigo", "nome", "regiao"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.nome),
    chaves: ["codigo"],
    colunas: [
      { chave: "codigo", rotulo: "Código", largura: 90 },
      { chave: "nome", rotulo: "Nome", largura: 300 },
      { chave: "regiao", rotulo: "Região (código)", largura: 130, ref: "regiao" },
      { chave: "regiao_nm", rotulo: "Descrição da Região", largura: 220, derivada: true },
    ],
  },
  {
    slug: "materiais-insumos",
    titulo: "Material e Insumos",
    // o relatório sai do sistema como "ExportTCO13TExportToExcel-NNNN"
    arquivos: ["materiais e insumos", "material e insumos", "produtos", "materiais", "exporttco13texporttoexcel"],
    obrigatorias: ["codigo", "descricao", "grupo_de_produto", "unidade_medida_consumo"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.descricao),
    chaves: ["codigo"],
    grande: true,
    abas: [
      { id: "insumos", rotulo: "Insumos", descricao: "Grupos 01.02.00 a 01.02.35 (defensivos, adjuvantes, fertilizantes…), com os dados de aplicação." },
      { id: "materiais", rotulo: "Materiais", descricao: "Os demais grupos do cadastro." },
    ],
    colunas: [
      { chave: "codigo", rotulo: "Código", alinhar: "direita" },
      { chave: "descricao", rotulo: "Descrição", largura: 300 },
      { chave: "nome_comercial", rotulo: "Nome Comercial", largura: 160, aba: "insumos" },
      { chave: "principio_ativo", rotulo: "Princípio Ativo", largura: 260, aba: "insumos" },
      { chave: "concentracao", rotulo: "Concentração", largura: 150, aba: "insumos" },
      { chave: "classe_agronomica", rotulo: "Classe Agronômica", largura: 170, aba: "insumos" },
      { chave: "categoria", rotulo: "Categoria", largura: 170, aba: "insumos" },
      { chave: "un_aplicacao", rotulo: "Un. Aplicação", alinhar: "centro", aba: "insumos" },
      { chave: "descricao_complementar_1", rotulo: "Descrição Complementar", largura: 220, aba: "materiais" },
      { chave: "grupo_de_produto", rotulo: "Grupo" },
      { chave: "unidade_medida_consumo", rotulo: "UM", alinhar: "centro" },
      { chave: "tipo_de_produto", rotulo: "Tipo de Produto" },
    ],
  },
  {
    slug: "etapa",
    titulo: "Etapa",
    arquivos: ["etapa", "etapas"],
    obrigatorias: ["codigo_da_etapa", "descricao_da_etapa"],
    codigo: (d) => texto(d.codigo_da_etapa),
    nome: (d) => texto(d.descricao_da_etapa),
    chaves: ["codigo_da_etapa"],
    colunas: [
      { chave: "codigo_da_etapa", rotulo: "Código", alinhar: "direita", largura: 90 },
      { chave: "descricao_da_etapa", rotulo: "Descrição da Etapa", largura: 300 },
      { chave: "ativa", rotulo: "Ativa", alinhar: "centro" },
    ],
  },
  {
    slug: "tipo-aplicacao",
    titulo: "Tipo Aplicação",
    // "Tipos de aplicações agrícolas" sai do sistema como "ExportWWTAG55TExportToExcel"
    arquivos: ["tipo aplicacao", "tipos de aplicacao", "tipo de aplicacao", "tipos de aplicacoes agricolas", "exportwwtag55texporttoexcel"],
    obrigatorias: ["codigo", "descricao"],
    // o mesmo código aparece com mais de uma descrição (ex.: 14 Aplicação Localizada e 14 Colheitabilidade): a chave é o par
    codigo: (d) => `${texto(d.codigo)}|${texto(d.descricao)}`,
    nome: (d) => texto(d.descricao),
    chaves: ["codigo", "descricao"],
    colunas: [
      { chave: "codigo", rotulo: "Código", alinhar: "direita", largura: 90 },
      { chave: "descricao", rotulo: "Descrição", largura: 320 },
    ],
  },
  {
    slug: "classificacao-operacoes",
    titulo: "Classificação de Operações",
    // sai do sistema como "ExportWWTSC41TExportToExcel"
    arquivos: ["classificacao de operacoes", "classificacoes de operacoes", "exportwwtsc41texporttoexcel"],
    obrigatorias: ["codigo", "descricao", "producao_da_operacao"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.descricao),
    chaves: ["codigo"],
    colunas: [
      { chave: "codigo", rotulo: "Código", alinhar: "direita", largura: 90 },
      { chave: "descricao", rotulo: "Descrição", largura: 280 },
      { chave: "producao_da_operacao", rotulo: "Produção da Operação", alinhar: "direita", largura: 160 },
    ],
  },
  {
    slug: "tipos-despesa",
    titulo: "Tipos de Despesa",
    // sai do sistema como "ExportWWTSC39TExportToExcel" (cada tipo repetido uma vez por safra do rateio)
    arquivos: ["tipos de despesa", "tipos de despesas", "tipo de despesa", "exportwwtsc39texporttoexcel"],
    obrigatorias: ["codigo", "descricao", "forma_de_amortizacao"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.descricao),
    chaves: ["codigo"],
    colunas: [
      { chave: "codigo", rotulo: "Código", alinhar: "direita", largura: 90 },
      { chave: "descricao", rotulo: "Descrição", largura: 260 },
      { chave: "forma_de_amortizacao", rotulo: "Forma de Amortização", alinhar: "centro", largura: 170 },
      { chave: "total_do_percentual", rotulo: "Total do Percentual", alinhar: "direita", largura: 150 },
    ],
  },
  {
    slug: "operacoes",
    titulo: "Operações",
    // sai do sistema como "ExportWWTSC42TExportToExcel"
    arquivos: ["operacoes", "operacao", "exportwwtsc42texporttoexcel"],
    obrigatorias: ["codigo", "descricao_da_operacao", "unidade_de_medida"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.descricao_da_operacao),
    chaves: ["codigo"],
    colunas: [
      { chave: "codigo", rotulo: "Código", alinhar: "direita", largura: 90 },
      { chave: "descricao_da_operacao", rotulo: "Descrição da Operação", largura: 320 },
      // a descrição vem do cadastro Tipo Operação; o código não é barrado (o relatório exportado traz D, O, P e R)
      { chave: "tipo", rotulo: "Tipo", alinhar: "centro", ref: "tipos-operacao", refLivre: true },
      { chave: "tipo_nm", rotulo: "Tipo Operação", largura: 150, derivada: true },
      { chave: "grupo", rotulo: "Grupo" },
      { chave: "descricao_do_grupo", rotulo: "Descrição do Grupo", largura: 220 },
      { chave: "grau", rotulo: "Grau", alinhar: "direita" },
      { chave: "unidade_de_medida", rotulo: "UM", alinhar: "centro" },
      { chave: "descricao_unidade_de_medida", rotulo: "Descrição UM", largura: 130 },
      // o 2º "Código" do relatório é o da Classificação de Operações
      { chave: "codigo_2", rotulo: "Classificação (código)", alinhar: "direita", largura: 150, ref: "classificacao-operacoes" },
      { chave: "codigo_2_nm", rotulo: "Classificação", largura: 160, derivada: true },
      { chave: "codigo_da_etapa", rotulo: "Código da Etapa", alinhar: "direita" },
      { chave: "descricao_da_etapa", rotulo: "Descrição da Etapa", largura: 220 },
      { chave: "codigo_de_despesa", rotulo: "Tipo de Despesa (código)", alinhar: "direita", largura: 160, ref: "tipos-despesa" },
      { chave: "codigo_de_despesa_nm", rotulo: "Tipo de Despesa", largura: 160, derivada: true },
      { chave: "centro_de_custo", rotulo: "Centro de Custo", alinhar: "direita" },
      { chave: "nome_do_centro_de_custo", rotulo: "Nome do Centro de Custo", largura: 200 },
      { chave: "valor_unitario", rotulo: "Valor Unitário", alinhar: "direita" },
      { chave: "vinculo_c_operacao_agricola_realizada_por_terceiros", rotulo: "Vínculo c/ Operação de Terceiros", alinhar: "direita", largura: 200 },
      { chave: "descricao_do_vinculo", rotulo: "Descrição do Vínculo", largura: 180 },
    ],
  },
  {
    slug: "recursos",
    titulo: "Recurso",
    arquivos: ["recurso", "recursos"],
    obrigatorias: ["codigo", "descricao"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.descricao),
    chaves: ["codigo"],
    colunas: [
      { chave: "codigo", rotulo: "Código", alinhar: "direita", largura: 110 },
      { chave: "descricao", rotulo: "Descrição", largura: 360 },
    ],
  },
  {
    slug: "grupos-operacoes",
    titulo: "Grupos de Operações",
    arquivos: ["grupos de operacoes", "grupo de operacoes", "grupos das operacoes"],
    obrigatorias: ["operacao", "grupo"],
    codigo: (d) => texto(d.operacao),
    nome: (d) => texto(d.grupo_nm) || texto(d.grupo),
    chaves: ["operacao"],
    colunas: [
      {
        chave: "operacao",
        rotulo: "Operação (código)",
        alinhar: "direita",
        largura: 140,
        ref: "operacoes",
        traz: { classificacao: { campo: "codigo_2", ref: "classificacao-operacoes" } },
      },
      { chave: "operacao_nm", rotulo: "Operação", largura: 300, derivada: true },
      { chave: "classificacao", rotulo: "Classificação da Operação", largura: 190, derivada: true },
      // grupo do cadastro Grupo Op. Dashboard: aceita o código ou o nome do grupo (planilha) e guarda o código
      { chave: "grupo", rotulo: "Grupo (código)", alinhar: "direita", largura: 120, ref: "grupos-dashboard", aceitaNome: true, traz: { ordem: "ordem" } },
      { chave: "grupo_nm", rotulo: "Grupo (Dashboard de Atividades)", largura: 240, derivada: true },
      { chave: "ordem", rotulo: "Ordem do grupo", alinhar: "direita", largura: 120, derivada: true },
    ],
  },
  {
    // grupos das operações no Dashboard de Atividades (a ordem é a das linhas no dashboard e no PDF)
    slug: "grupos-dashboard",
    titulo: "Grupo Op. Dashboard",
    arquivos: ["grupo op dashboard", "grupos op dashboard", "grupos do dashboard", "grupo do dashboard"],
    obrigatorias: ["codigo", "grupo"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.grupo).toUpperCase(),
    chaves: ["codigo"],
    // o mesmo grupo não fica em dois códigos, nem com outra grafia (acento, maiúsculas, espaços)
    nomeUnico: true,
    colunas: [
      { chave: "codigo", rotulo: "Código", alinhar: "direita", largura: 100 },
      { chave: "grupo", rotulo: "Grupo", largura: 300 },
      { chave: "ordem", rotulo: "Ordem no dashboard", alinhar: "direita", largura: 150 },
    ],
  },
  {
    slug: "tipos-operacao",
    titulo: "Tipo Operação",
    arquivos: ["tipo operacao", "tipos operacao", "tipo de operacao", "tipos de operacao"],
    obrigatorias: ["codigo", "tipo_operacao"],
    codigo: (d) => texto(d.codigo),
    nome: (d) => texto(d.tipo_operacao),
    chaves: ["codigo"],
    colunas: [
      { chave: "codigo", rotulo: "Código", alinhar: "centro", largura: 100 },
      { chave: "tipo_operacao", rotulo: "Tipo Operação", largura: 320 },
    ],
  },
  {
    slug: "responsaveis-os",
    titulo: "Responsáveis",
    arquivos: ["responsaveis os", "responsaveis o s", "cadastro responsaveis", "responsaveis das os"],
    obrigatorias: ["area", "matricula", "nome_do_responsavel"],
    codigo: (d) => texto(d.matricula),
    nome: (d) => texto(d.nome_do_responsavel),
    chaves: ["matricula"],
    colunas: [
      { chave: "matricula", rotulo: "Matrícula", alinhar: "direita", largura: 110 },
      { chave: "nome_do_responsavel", rotulo: "Nome do Responsável", largura: 300 },
      { chave: "area", rotulo: "Área", largura: 220 },
    ],
  },
  {
    slug: "faixas-dias-os",
    titulo: "Faixas Dias",
    arquivos: ["faixas dias", "faixas de dias"],
    obrigatorias: ["faixa", "de_dias"],
    codigo: (d) => texto(d.faixa),
    nome: (d) => texto(d.descricao),
    chaves: ["faixa"],
    colunas: [
      { chave: "faixa", rotulo: "Ordem", alinhar: "direita", largura: 80 },
      { chave: "descricao", rotulo: "Descrição", largura: 240 },
      { chave: "de_dias", rotulo: "De (dias)", alinhar: "direita", largura: 100 },
      { chave: "ate_dias", rotulo: "Até (dias) — vazio = sem limite", alinhar: "direita", largura: 200 },
    ],
  },
  {
    slug: "funcionarios",
    titulo: "Funcionários",
    // o relatório de Pessoas sai do sistema como "ExportWWTFR05TExportToExcel"
    arquivos: ["funcionarios", "pessoas", "exportwwtfr05texporttoexcel"],
    obrigatorias: ["pessoa", "nome_pessoa", "matricula"],
    codigo: (d) => texto(d.pessoa),
    nome: (d) => texto(d.nome_pessoa),
    chaves: ["pessoa"],
    grande: true,
    colunas: [
      { chave: "pessoa", rotulo: "Pessoa", alinhar: "direita", largura: 90 },
      { chave: "nome_pessoa", rotulo: "Nome", largura: 280 },
      { chave: "matricula", rotulo: "Matrícula", alinhar: "direita" },
      { chave: "ativo", rotulo: "Ativo", alinhar: "centro" },
      { chave: "motivo_da_inatividade", rotulo: "Motivo da Inatividade", largura: 160 },
      { chave: "descricao", rotulo: "Hora / Função", largura: 160 },
      { chave: "centro_de_custo", rotulo: "Centro de Custo", alinhar: "direita" },
      { chave: "nome_centro_de_custo", rotulo: "Nome do Centro de Custo", largura: 200 },
      { chave: "codigo_da_frente", rotulo: "Frente", alinhar: "direita" },
      { chave: "descricao_da_frente", rotulo: "Descrição da Frente", largura: 180 },
      { chave: "nome_do_empregador", rotulo: "Empregador", largura: 240 },
      { chave: "interna_externa", rotulo: "Interna / Externa", alinhar: "centro" },
      { chave: "tipo_pessoa", rotulo: "Tipo Pessoa", alinhar: "centro" },
    ],
  },
];

export function specPorSlug(slug) {
  return CADASTROS_SPEC.find((s) => s.slug === slug);
}

/** Cadastro sugerido pelo nome do arquivo ("Tipo de Solo.xlsx" -> tipos-solo). */
export function specPorNomeArquivo(nomeArquivo) {
  const base = normalizarTexto(nomeArquivo.replace(/\.[^.]+$/, ""));
  return CADASTROS_SPEC.find((s) => s.arquivos.some((a) => base === a || base.startsWith(`${a} `)));
}
