/** Cadastros de apoio (Configurações > Cadastros), na ordem do menu. "usuarios"
 * tem tela própria; os demais ainda são páginas em construção. */
export const CADASTROS: { slug: string; label: string }[] = [
  { slug: "etapa", label: "Etapa" },
  { slug: "frente", label: "Frente" },
  { slug: "tipo-colheita", label: "Tipo Colheita" },
  { slug: "tipo-corte", label: "Tipo de Corte" },
  { slug: "variedades", label: "Variedades" },
  { slug: "regiao", label: "Região" },
  { slug: "bloco", label: "Bloco" },
  { slug: "tipo-plantio", label: "Tipo Plantio" },
  { slug: "tipo-propriedade", label: "Tipo Propriedade" },
  { slug: "tipo", label: "Tipo" },
  { slug: "estagio", label: "Estágio" },
  { slug: "espacamento", label: "Espaçamento" },
  { slug: "classificacao-operacoes", label: "Classificação de Operações" },
  { slug: "operacoes", label: "Operações" },
  { slug: "grupos-operacoes", label: "Grupos de Operações" },
  { slug: "recursos", label: "Recurso" },
  { slug: "tipos-despesa", label: "Tipos de Despesa" },
  { slug: "safras", label: "Safras" },
  { slug: "sistema-aplicacao", label: "Sistema de Aplicação" },
  { slug: "tipo-aplicacao", label: "Tipo Aplicação" },
  { slug: "fazendas", label: "Fazenda" },
  { slug: "solos", label: "Solos" },
  { slug: "tipos-solo", label: "Tipos de Solo" },
  { slug: "maturacao", label: "Maturação" },
  { slug: "estados", label: "Estados" },
  { slug: "fornecedores-prestadores", label: "Fornecedores e Prestadores" },
  { slug: "funcionarios", label: "Funcionários" },
  { slug: "materiais-insumos", label: "Material e Insumos" },
  { slug: "usuarios", label: "Usuários" },
];
